services:
    ecommerce.backend:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: ecommerce-backend
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8017}:80'
        volumes:
            - '.:/var/www/'
        networks:
            - ecommerce-backend
        depends_on:
            - mysqldb
    mysqldb:
        image: 'mysql:8.0.36-debian'
        ports:
            - '${FORWARD_DB_PORT:-3317}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'ecommerce-backend-mysqldb:/var/lib/mysql'
        networks:
            - ecommerce-backend
networks:
    ecommerce-backend:
        driver: bridge
volumes:
    ecommerce-backend-mysqldb:
        driver: local
